version: '2'
services:
    db: 
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3307:3306"
    es:
        image: elasticsearch:8.2.0
        
        ports:
        - "9200:9200"
        - "9300:9300"
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        mem_limit: 1g
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node
            - ES_HOST=es
        cap_add:
            - IPC_LOCK
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
    redis:
        image: 'redis:5-alpine'
        command: redis-server
        ports:
          - '6379:6379'
    app: 
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes: 
            - ".:/app"
        ports: 
            - "3001:3000"
        depends_on:
            - db
            - redis
            - es
        links:
            - db
            - redis
            - es
        environment:
            DB_USER: root
            DB_NAME: app
            DB_PASSWORD: password
            DB_HOST: db
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_URL: redis://localhost:6379/1
            ES_HOST: es
            ELASTIC_PORT: "9200"
    sidekiq:
        build: .
        command: bundle exec sidekiq
        volumes:
          - .:/app
        environment:
            DB_USER: root
            DB_NAME: app
            DB_PASSWORD: password
            DB_HOST: db
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_URL: redis
        depends_on:
            - redis
            - db
        links:
            - db
            - redis
volumes:
  elasticsearch-data:
    driver: local